FROM frolvlad/plpine-oraclejdk8-slim
VOLUM /tmp
ADD sprms-1.war app.war
RUN sh -c 'touch /app.war'
ENV JAVA_OPTS=""
ENTRYPOINT ["sh","-c","java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -war /app.war"]